services:
  api-gateway:
    build:
      context: .
      dockerfile: ./services/api-gateway/Dockerfile
    volumes:
      - ./services/api-gateway:/var/www/api-gateway
      - /var/www/api-gateway/vendor
    environment:
      - APP_ENV=local
      - CONTAINER_ROLE=app
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_VHOST=/
    develop:
      watch:
        - action: sync
          path: services/api-gateway
          target: /var/www/api-gateway
          ignore:
            - vendor/
        - action: rebuild
          path: services/api-gateway/composer.json
    networks:
      - microservices-network
    depends_on:
      - rabbitmq

  auth-service:
    build:
      context: .
      dockerfile: ./services/auth-service/Dockerfile
    volumes:
      - ./services/auth-service:/var/www/auth-service
      - /var/www/auth-service/vendor
    environment:
      - APP_ENV=local
      - CONTAINER_ROLE=app
      - DB_HOST=${DB_AUTH_HOST}
    develop:
      watch:
        - action: sync
          path: services/auth-service
          target: /var/www/auth-service
          ignore:
            - vendor/
        - action: rebuild
          path: services/auth-service/composer.json
    networks:
      - microservices-network
    depends_on:
      - auth-db
      
  auth-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: auth_service_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - ${DB_AUTH_EXTERNAL_PORT}:3306
    networks:
      - microservices-network

  messages-broker:
    build:
      context: .
      dockerfile: ./services/messages-broker/Dockerfile
    volumes:
      - ./services/messages-broker:/var/www/messages-broker
      - /var/www/messages-broker/vendor
    environment:
      - APP_ENV=local
      - CONTAINER_ROLE=app
      - DB_HOST=${DB_MESSAGES_BROKER_HOST}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    develop:
      watch:
        - action: sync
          path: services/messages-broker
          target: /var/www/messages-broker
          ignore:
            - vendor/
        - action: rebuild
          path: services/messages-broker/composer.json
    networks:
      - microservices-network
    depends_on:
      - messages-broker-db
      - rabbitmq

  messages-broker-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: messages_broker
      MYSQL_ROOT_PASSWORD: root
    ports:
      - ${DB_MESSAGES_BROKER_EXTERNAL_PORT}:3306
    networks:
      - microservices-network

  addresses-service:
    build:
      context: .
      dockerfile: ./services/addresses-service/Dockerfile
    volumes:
      - ./services/addresses-service:/var/www/addresses-service
      - /var/www/addresses-service/vendor
    environment:
      - APP_ENV=local
      - CONTAINER_ROLE=app
      - DB_HOST=${DB_ADDRESSES_HOST}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_VHOST=/
    develop:
      watch:
        - action: sync
          path: services/addresses-service
          target: /var/www/addresses-service
          ignore:
            - vendor/
        - action: rebuild
          path: services/addresses-service/composer.json
    networks:
      - microservices-network
    depends_on:
      - addresses-db
      - rabbitmq

  addresses-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: addresses_service
      MYSQL_ROOT_PASSWORD: root
    ports:
      - ${DB_ADDRESSES_EXTERNAL_PORT}:3306
    networks:
      - microservices-network

  products-service:
    build:
      context: .
      dockerfile: ./services/products-service/Dockerfile
    volumes:
      - ./services/products-service:/var/www/products-service
      - ./shared:/var/www/shared
      - /var/www/products-service/vendor
    environment:
      - APP_ENV=local
      - CONTAINER_ROLE=app
      - DB_HOST=${DB_PRODUCTS_HOST}
    develop:
      watch:
        - action: sync
          path: services/products-service
          target: /var/www/products-service
          ignore:
            - vendor/
        - action: rebuild
          path: services/products-service/composer.json
    networks:
      - microservices-network
    depends_on:
      - products-db

  products-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: products_service_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - ${DB_PRODUCTS_EXTERNAL_PORT}:3306
    networks:
      - microservices-network

  baskets-service:
    build:
      context: .
      dockerfile: ./services/baskets-service/Dockerfile
    volumes:
      - ./services/baskets-service:/var/www/baskets-service
      - ./shared:/var/www/shared
      - /var/www/baskets-service/vendor
    environment:
      - APP_ENV=local
      - CONTAINER_ROLE=app
      - DB_HOST=${DB_BASKETS_HOST}
    develop:
      watch:
        - action: sync
          path: services/baskets-service
          target: /var/www/baskets-service
          ignore:
            - vendor/
        - action: rebuild
          path: services/baskets-service/composer.json
    networks:
      - microservices-network
    depends_on:
      - baskets-db

  baskets-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: baskets_service_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - ${DB_BASKETS_EXTERNAL_PORT}:3306
    volumes:
      - baskets-db-data:/var/lib/mysql
    networks:
      - microservices-network

  orders-service:
    build:
      context: .
      dockerfile: ./services/orders-service/Dockerfile
    volumes:
      - ./services/orders-service:/var/www/orders-service
      - ./shared:/var/www/shared
      - /var/www/orders-service/vendor
    environment:
      - APP_ENV=local
      - CONTAINER_ROLE=app
      - DB_HOST=${DB_ORDERS_HOST}
    develop:
      watch:
        - action: sync
          path: services/orders-service
          target: /var/www/orders-service
          ignore:
            - vendor/
        - action: rebuild
          path: services/orders-service/composer.json
    networks:
      - microservices-network
    depends_on:
      - orders-db

  orders-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: orders_service_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - ${DB_ORDERS_EXTERNAL_PORT}:3306
    volumes:
      - orders-db-data:/var/lib/mysql
    networks:
      - microservices-network

  deliveries-service:
    build:
      context: .
      dockerfile: ./services/deliveries-service/Dockerfile
    volumes:
      - ./services/deliveries-service:/var/www/deliveries-service
      - ./shared:/var/www/shared
      - /var/www/deliveries-service/vendor
    environment:
      - APP_ENV=local
      - CONTAINER_ROLE=app
      - DB_HOST=${DB_DELIVERIES_HOST}
    develop:
      watch:
        - action: sync
          path: services/deliveries-service
          target: /var/www/deliveries-service
          ignore:
            - vendor/
        - action: rebuild
          path: services/deliveries-service/composer.json
    networks:
      - microservices-network
    depends_on:
      - deliveries-db

  deliveries-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: deliveries_service_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - ${DB_DELIVERIES_EXTERNAL_PORT}:3306
    volumes:
      - deliveries-db-data:/var/lib/mysql
    networks:
      - microservices-network

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - microservices-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"  # Pour HTTPS
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./services/api-gateway:/var/www/api-gateway
      - ./services/auth-service:/var/www/auth-service
      - ./services/addresses-service:/var/www/addresses-service
      - ./services/products-service:/var/www/products-service
      - ./services/baskets-service:/var/www/baskets-service
      - ./services/deliveries-service:/var/www/deliveries-service
    develop:
      watch:
        - action: sync
          path: docker/nginx/conf.d
          target: /etc/nginx/conf.d
    networks:
      - microservices-network
    depends_on:
      - api-gateway
      - auth-service
      - addresses-service
      - products-service
      - baskets-service
      - deliveries-service
      - messages-broker

volumes:
  auth-db-data:
  addresses-db-data:
  products-db-data:
  baskets-db-data:
  orders-db-data:
  deliveries-db-data:
  rabbitmq-data:

networks:
  microservices-network:
    driver: bridge