apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
  namespace: e-commerce-prod
data:
  # Production environment settings
  APP_ENV: "production"
  APP_DEBUG: "false"
  LOG_LEVEL: "warning"
  
  # Production monitoring (full monitoring enabled)
  PROMETHEUS_ENABLED: "true"
  METRICS_PORT: "9090"
  LOG_CHANNEL: "syslog"
  
  # Production JWT (secure settings)
  JWT_TTL: "60"
  JWT_REFRESH_TTL: "20160"
  JWT_BLACKLIST_ENABLED: "true"
  
  # Production API (stricter rate limiting)
  API_RATE_LIMIT: "100"
  API_THROTTLE_ENABLED: "true"
  
  # Production domains
  FRONTEND_URL: "https://yourcompany.com"
  API_URL: "https://api.yourcompany.com"
  ADMIN_URL: "https://admin.yourcompany.com"
  
  # Production database (optimized settings)
  DB_CONNECTION: "mysql"
  DB_PORT: "3306"
  DB_CHARSET: "utf8mb4"
  DB_COLLATION: "utf8mb4_unicode_ci"
  
  # Production cache (Redis cluster)
  CACHE_DRIVER: "redis"
  REDIS_CLIENT: "predis"
  REDIS_CLUSTER: "true"
  
  # Production queue (RabbitMQ cluster)
  QUEUE_CONNECTION: "rabbitmq"
  RABBITMQ_HEARTBEAT: "60"
  
  # Production session (secure)
  SESSION_DRIVER: "redis"
  SESSION_LIFETIME: "120"
  SESSION_SECURE_COOKIE: "true"
  SESSION_HTTP_ONLY: "true"
  SESSION_SAME_SITE: "lax"
  
  # Production mail
  MAIL_MAILER: "smtp"
  MAIL_PORT: "587"
  MAIL_ENCRYPTION: "tls"
  
  # Production broadcasting
  BROADCAST_DRIVER: "redis"
  
  # Production filesystem
  FILESYSTEM_DISK: "s3"
  
  # Production security
  SECURITY_HEADERS_ENABLED: "true"
  CORS_ALLOWED_ORIGINS: "https://yourcompany.com,https://admin.yourcompany.com"