apiVersion: v1
kind: Service
metadata:
  name: products-service-mysql
  namespace: e-commerce
  labels:
    app: products-service-mysql
    component: database
    service: products
spec:
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
  selector:
    app: products-service-mysql
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-service-mysql
  namespace: e-commerce
  labels:
    app: products-service-mysql
    component: database
    service: products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-service-mysql
  template:
    metadata:
      labels:
        app: products-service-mysql
        component: database
        service: products
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "products-root-password"
        - name: MYSQL_DATABASE
          value: "products_service_db"
        - name: MYSQL_USER
          value: "products_user"
        - name: MYSQL_PASSWORD
          value: "products-password-change-this"
        ports:
        - containerPort: 3306
          name: mysql
        resources:
          requests:
            memory: 256Mi
            cpu: 200m
          limits:
            memory: 512Mi
            cpu: 500m
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: mysql-storage
        emptyDir: {}  # For development only