apiVersion: v1
kind: Service
metadata:
  name: websites-service-mysql
  namespace: e-commerce
  labels:
    app: websites-service-mysql
    component: database
    service: websites
spec:
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
  selector:
    app: websites-service-mysql
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: websites-service-mysql
  namespace: e-commerce
  labels:
    app: websites-service-mysql
    component: database
    service: websites
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websites-service-mysql
  template:
    metadata:
      labels:
        app: websites-service-mysql
        component: database
        service: websites
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        command:
        - docker-entrypoint.sh
        args:
        - mysqld
        - --default-authentication-plugin=mysql_native_password
        - --skip-log-bin
        stdin: true
        tty: true
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "websites_service_db"
        - name: MYSQL_USER
          value: "websites_user"
        - name: MYSQL_PASSWORD
          value: "websites-password-change-this"
        - name: MYSQL_ROOT_HOST
        ports:
        - containerPort: 3306
          name: mysql
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 500m
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 45
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: mysql-storage
        emptyDir: {}
      - name: init-script
        configMap:
          name: mysql-init-script
