# Prometheus Stack - Minikube Optimized Configuration
# Reduced resources for local development

prometheus:
  prometheusSpec:
    replicas: 1  # Single replica for dev
    retention: 7d  # Reduced retention
    retentionSize: 5GiB  # Reduced storage

    # Minimal storage
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi

    # Reduced resources
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: 500m

# Grafana configuration
grafana:
  enabled: true
  replicas: 1

  adminPassword: admin

  # Minimal persistence
  persistence:
    enabled: true
    size: 2Gi

  # Reduced resources
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 200m

# Alertmanager configuration
alertmanager:
  alertmanagerSpec:
    replicas: 1  # Single replica for dev
    retention: 24h  # Reduced retention

    # Minimal storage
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi

    # Reduced resources
    resources:
      requests:
        memory: 128Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 100m

# Node Exporter
nodeExporter:
  enabled: true
  resources:
    requests:
      memory: 30Mi
      cpu: 50m
    limits:
      memory: 50Mi
      cpu: 100m

# Kube State Metrics
kubeStateMetrics:
  enabled: true
  resources:
    requests:
      memory: 64Mi
      cpu: 50m
    limits:
      memory: 128Mi
      cpu: 100m

# Prometheus Node Exporter
prometheus-node-exporter:
  enabled: true
  resources:
    requests:
      memory: 30Mi
      cpu: 50m
    limits:
      memory: 50Mi
      cpu: 100m

# Disable some features for dev
defaultRules:
  create: true
  rules:
    etcd: false
    kubeScheduler: false
