# MySQL Operator for managing database instances
apiVersion: v1
kind: Namespace
metadata:
  name: mysql-operator
---
# MySQL InnoDB Cluster for high availability
apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mysql-cluster
  namespace: e-commerce
spec:
  instances: 3
  secretName: mysql-root-secret
  tlsUseSelfSigned: true
  
  # MySQL configuration
  mysql:
    version: "8.0.35"
    
    # Resource allocation
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1000m
        memory: 2Gi
    
    # Storage configuration
    datadirVolumeClaimTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
      storageClassName: ""
    
    # MySQL configuration
    mycnf: |
      [mysqld]
      # InnoDB settings
      innodb_buffer_pool_size = 1G
      innodb_log_file_size = 256M
      innodb_flush_log_at_trx_commit = 1
      innodb_file_per_table = 1
      
      # Performance settings
      max_connections = 200
      query_cache_type = 1
      query_cache_size = 128M
      tmp_table_size = 64M
      max_heap_table_size = 64M
      
      # Character set
      character_set_server = utf8mb4
      collation_server = utf8mb4_unicode_ci
      
      # Binary logging
      log_bin = mysql-bin
      binlog_format = ROW
      expire_logs_days = 7
      
      # Slow query log
      slow_query_log = 1
      slow_query_log_file = /var/lib/mysql/slow.log
      long_query_time = 2
      
      # Error log
      log_error = /var/lib/mysql/error.log
      
      # General log (disable in production)
      general_log = 0
  
  # Router configuration for load balancing
  router:
    instances: 2
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

---
# Secret for MySQL root password
apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-secret
  namespace: e-commerce
type: Opaque
stringData:
  rootPassword: "your-super-secure-root-password-change-this"
  rootHost: "%"

---
# Individual service databases
apiVersion: mysql.oracle.com/v2
kind: MySQLBackup
metadata:
  name: daily-backup
  namespace: e-commerce
spec:
  clusterName: mysql-cluster
  backupProfileName: daily-backup-profile

---
# Backup profile for automated backups
apiVersion: mysql.oracle.com/v2
kind: MySQLBackupProfile
metadata:
  name: daily-backup-profile
  namespace: e-commerce
spec:
  # S3-compatible storage for backups
  storage:
    s3:
      bucketName: mysql-backups
      prefix: e-commerce/
      config: s3-backup-config
      credentials: s3-backup-credentials
  
  # Backup schedule
  schedule: "0 2 * * *"  # Daily at 2 AM
  
  # Retention policy
  retentionPolicy:
    days: 30
    
---
# Service for external access to MySQL
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: e-commerce
  labels:
    app: mysql
    component: database
spec:
  selector:
    mysql.oracle.com/cluster: mysql-cluster
    mysql.oracle.com/role: primary
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
  type: ClusterIP

---
# ServiceMonitor for MySQL metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysql-cluster
  namespace: e-commerce
  labels:
    app: mysql
    component: database
spec:
  selector:
    matchLabels:
      mysql.oracle.com/cluster: mysql-cluster
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s