apiVersion: v1
kind: Namespace
metadata:
  name: e-commerce
  labels:
    environment: development
---
apiVersion: v1
kind: Namespace
metadata:
  name: e-commerce-monitoring
  labels:
    environment: development
---
apiVersion: v1
kind: Namespace
metadata:
  name: e-commerce-messaging
  labels:
    environment: development