apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: e-commerce-platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/DevGenius-IT/e-commerce-back  # À modifier avec votre repo
    targetRevision: dev
    path: k8s/overlays/development
  destination:
    server: https://kubernetes.default.svc
    namespace: e-commerce
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: e-commerce-messaging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/DevGenius-IT/e-commerce-back  # À modifier avec votre repo
    targetRevision: dev
    path: k8s/base/services
  destination:
    server: https://kubernetes.default.svc
    namespace: e-commerce-messaging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true