apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  annotations:
    description: Base configuration for e-commerce microservices platform
  name: e-commerce-base

  # Core infrastructure
  
  # Configuration and secrets
  
  # Supporting services
resources:
- namespace.yaml
- configmaps/global-config.yaml
- secrets/secrets-template.yaml
- services/redis.yaml
- services/addresses-mysql.yaml
- services/auth-mysql.yaml
- services/baskets-mysql.yaml
- services/contacts-mysql.yaml
- services/deliveries-mysql.yaml
- services/newsletters-mysql.yaml
- services/orders-mysql.yaml
- services/products-mysql.yaml
- services/questions-mysql.yaml
- services/sav-mysql.yaml
- services/websites-mysql.yaml
- services/rabbitmq.yaml
- minio-deployment.yaml

labels:
- pairs:
    managed-by: kustomize
    project: e-commerce-microservices

# Global patches that apply to all resources

# Common annotations for all resources
commonAnnotations:
  deployment-tool: kustomize
  platform: kubernetes
  
# Images to be used (can be overridden in overlays)
images:
- name: redis
  newTag: 7-alpine
