# This is a template file for secrets
# In real environments, use External Secrets Operator with Vault/AWS Secrets Manager

apiVersion: v1
kind: Secret
metadata:
  name: global-secrets
  namespace: e-commerce
  labels:
    app: global-secrets
    component: security
type: Opaque
stringData:
  # JWT Secrets (CHANGE IN PRODUCTION)
  JWT_SECRET: "your-super-secret-jwt-key-change-this-in-production"
  
  # Database Secrets (CHANGE IN PRODUCTION)
  DB_ROOT_PASSWORD: "root-password-change-this"
  
  # RabbitMQ Secrets (CHANGE IN PRODUCTION)
  RABBITMQ_USER: "admin"
  RABBITMQ_PASSWORD: "admin-password"
  RABBITMQ_MANAGEMENT_USER: "admin"
  RABBITMQ_MANAGEMENT_PASSWORD: "admin-password"
  
  # Redis Secrets (CHANGE IN PRODUCTION)
  REDIS_PASSWORD: "redis-password-change-this"
  
  # Application Secrets
  APP_KEY: "base64:your-laravel-app-key-here"
  
  # Email Secrets (if needed)
  MAIL_PASSWORD: "your-email-password"
  
  # Monitoring Secrets
  GRAFANA_ADMIN_PASSWORD: "admin-password-change-this"
---
# Individual service secrets template
apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
  namespace: e-commerce
  labels:
    app: auth-service
    component: security
type: Opaque
stringData:
  DB_HOST: "auth-service-mysql.e-commerce.svc.cluster.local"
  DB_DATABASE: "auth_service_db"
  DB_USERNAME: "auth_user"
  DB_PASSWORD: "auth-password-change-this"
---
apiVersion: v1
kind: Secret
metadata:
  name: products-service-secrets
  namespace: e-commerce
  labels:
    app: products-service
    component: security
type: Opaque
stringData:
  DB_HOST: "products-service-mysql.e-commerce.svc.cluster.local"
  DB_DATABASE: "products_service_db"
  DB_USERNAME: "products_user"
  DB_PASSWORD: "products-password-change-this"
---
apiVersion: v1
kind: Secret
metadata:
  name: baskets-service-secrets
  namespace: e-commerce
  labels:
    app: baskets-service
    component: security
type: Opaque
stringData:
  DB_HOST: "baskets-service-mysql.e-commerce.svc.cluster.local"
  DB_DATABASE: "baskets_service_db"
  DB_USERNAME: "baskets_user"
  DB_PASSWORD: "baskets-password-change-this"
---
apiVersion: v1
kind: Secret
metadata:
  name: orders-service-secrets
  namespace: e-commerce
  labels:
    app: orders-service
    component: security
type: Opaque
stringData:
  DB_HOST: "orders-service-mysql.e-commerce.svc.cluster.local"
  DB_DATABASE: "orders_service_db"
  DB_USERNAME: "orders_user"
  DB_PASSWORD: "orders-password-change-this"
---
apiVersion: v1
kind: Secret
metadata:
  name: addresses-service-secrets
  namespace: e-commerce
  labels:
    app: addresses-service
    component: security
type: Opaque
stringData:
  DB_HOST: "addresses-service-mysql.e-commerce.svc.cluster.local"
  DB_DATABASE: "addresses_service_db"
  DB_USERNAME: "addresses_user"
  DB_PASSWORD: "addresses-password-change-this"
---
apiVersion: v1
kind: Secret
metadata:
  name: contacts-service-secrets
  namespace: e-commerce
  labels:
    app: contacts-service
    component: security
type: Opaque
stringData:
  DB_HOST: "contacts-mysql.e-commerce.svc.cluster.local"
  DB_DATABASE: "contacts_service_db"
  DB_USERNAME: "contacts_user"
  DB_PASSWORD: "contacts-password-change-this"
---
apiVersion: v1
kind: Secret
metadata:
  name: deliveries-service-secrets
  namespace: e-commerce
  labels:
    app: deliveries-service
    component: security
type: Opaque
stringData:
  DB_HOST: "deliveries-mysql.e-commerce.svc.cluster.local"
  DB_DATABASE: "deliveries_service_db"
  DB_USERNAME: "deliveries_user"
  DB_PASSWORD: "deliveries-password-change-this"
---
apiVersion: v1
kind: Secret
metadata:
  name: newsletters-service-secrets
  namespace: e-commerce
  labels:
    app: newsletters-service
    component: security
type: Opaque
stringData:
  DB_HOST: "newsletters-mysql.e-commerce.svc.cluster.local"
  DB_DATABASE: "newsletters_service_db"
  DB_USERNAME: "newsletters_user"
  DB_PASSWORD: "newsletters-password-change-this"
---
apiVersion: v1
kind: Secret
metadata:
  name: sav-service-secrets
  namespace: e-commerce
  labels:
    app: sav-service
    component: security
type: Opaque
stringData:
  DB_HOST: "sav-mysql.e-commerce.svc.cluster.local"
  DB_DATABASE: "sav_service_db"
  DB_USERNAME: "sav_user"
  DB_PASSWORD: "sav-password-change-this"
---
apiVersion: v1
kind: Secret
metadata:
  name: questions-service-secrets
  namespace: e-commerce
  labels:
    app: questions-service
    component: security
type: Opaque
stringData:
  DB_HOST: "questions-mysql.e-commerce.svc.cluster.local"
  DB_DATABASE: "questions_service_db"
  DB_USERNAME: "questions_user"
  DB_PASSWORD: "questions-password-change-this"
---
apiVersion: v1
kind: Secret
metadata:
  name: websites-service-secrets
  namespace: e-commerce
  labels:
    app: websites-service
    component: security
type: Opaque
stringData:
  DB_HOST: "websites-mysql.e-commerce.svc.cluster.local"
  DB_DATABASE: "websites_service_db"
  DB_USERNAME: "websites_user"
  DB_PASSWORD: "websites-password-change-this"
---
apiVersion: v1
kind: Secret
metadata:
  name: messages-broker-secrets
  namespace: e-commerce
  labels:
    app: messages-broker
    component: security
type: Opaque
stringData:
  DB_HOST: "messages-mysql.e-commerce.svc.cluster.local"
  DB_DATABASE: "messages_broker_db"
  DB_USERNAME: "messages_user"
  DB_PASSWORD: "messages-password-change-this"